fix: remove or update broken urls
DC-Resources-Wiki/Discord-Resources-Wiki pull request #45
Opened 2024-10-26 04:59 UTC by Yareaj

## Name of Resource: All Wiki

## Description of Resource: A cleanse of the wiki were broken URLs have been removed or replaced where possible!

## Discord ID(s) of the Creator(s): 518666147441278998

2024-10-26 12:59 UTC, mezotv requested changes

2024-10-26 12:59 UTC, mezotv commented on wiki/resources/official-badges.md
> +      <td>Owning a server that meets Discords partner <a href="https://i.imgur.com/QhdDRNC.png">requirements</a> and got accepted for a partnership. (No longer available)</td>
The badge is already set to unobtainale doesnt make sense to repeat yourself
```suggestion
      <td>Owning a server that meets Discords partner <a href="https://i.imgur.com/QhdDRNC.png">requirements</a> and got accepted for a partnership.</td>
```

2024-10-27 05:11 UTC, mezotv approved these changes

2024-12-02 05:55 UTC, JantsoP approved these changes

2024-12-02 05:55 UTC, merged